### ISSUE TITLE
On firmware 1.1, if your Platform JSON files from the Simple USA theme are added to \Platforms, openFPGA crashes on launch.

### ISSUE THREAD

**Issue by ReanimationXP** [Shissa43/Analogue-Pocket-Platform-Art#1]
On firmware 1.1, if your Platform JSON files from the Simple USA theme are added to \Platforms, openFPGA crashes on launch.  Something is broken with the Platform JSON files.  Overwriting them with Spiritualized1997's JSONs and images fixes the crash.

**Comment by neil-morrison44** [comment]
It's this line: https://github.com/Shissa43/Analogue-Pocket-Platform-Art/blob/main/Simple_platforms/Simple_USA/Platforms/genesis.json#L5

Also the root cause of https://github.com/neil-morrison44/pocket-sync/issues/142 (but I really should be dealing with the error better)

**Comment by Shissa43** [comment]
Fixed all the related JSON files
