### ISSUE TITLE
`Home_JAPAN` & `Home_USA` should be in separate zips in the release

### ISSUE THREAD

**Issue by neil-morrison44** [Shissa43/Analogue-Pocket-Platform-Art#4]
Hey, 
I'm making some changes to Pocket Sync to optimise the Platform Image & Data part - noticed that the `Home` variant has two sets of platform images nested together.

The app's probably just showing whichever image it happens to encounter first for the HOME variant, if you want them both to appear they'd need to be separate zips with them both appearing as variants in this list: https://github.com/mattpannella/pupdate/blob/main/image_packs.json#L49-L58 (I'm still just using Matt's JSON as the source of truth...)

Presumably pupdate has similar issues but I'm not sure

**Comment by Shissa43** [comment]
Thanks for the heads-up, I have an upcoming update at the end of the month, i will separate Home and Simple in their respective USA/JP ZIPs.
Regards
